### PR TITLE
implemented dark mode

### PR DESCRIPTION
**Pull request by Nipunkhattri**
Hello!
 I have implemented the dark mode which is working properly

### CODE REVIEW

**Comment by rucha0702** [comment]
Hi, thanks for the efforts! Could you please tag the issue(number) that it solves if it was assigned to you?

**Comment by Nipunkhattri** [comment]
The pull request is related to issue #4

**Comment by rucha0702** [comment]
> The pull request is related to issue #4

#4 has not been labelled yet, I'd suggest you to drop a comment at #13 to be assigned.

**Comment by Nipunkhattri** [comment]
please merge this pr..

**Comment by Nipunkhattri** [comment]
i have implemented dark mode on home page..

**Comment by RitikaGarg-tech** [comment]
Thanks for your efforts! Could you try to take a reference from the design for dark mode?

**Comment by Nipunkhattri** [comment]
I am closing this pr and making a new pr and I will push their ..

**Pull request closed without merging**
